In [3]:
import numpy as np

In [4]:
x=np.array([2,1,5,4,5,4,8,3,8,9])

In [5]:
print x

[2 1 5 4 5 4 8 3 8 9]


In [6]:
type(x)

numpy.ndarray

In [10]:
y = np.zeros((5, 10))

In [11]:
print y

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [14]:
np.dot(y, x, axis=1)

TypeError: 'axis' is an invalid keyword argument for this function